<a href="https://colab.research.google.com/github/ashikaj23/DSA_trainingSession/blob/main/kkem22_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10
x

10

In [ ]:
x = 'nithin'
x

'nithin'

In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
type(L[0])

int

In [ ]:
L1 = [1,'hi',True]
L1

[1, 'hi', True]

In [ ]:
[type(item) for item in L1]

[int, str, bool]

In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

# Numpy- numerical Python

In [ ]:
import numpy as np

Create numpy array

In [ ]:
# From list
list1 = [1,2,3,4]
np.array(list1)

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

a+b

array([ 5,  7,  9, 11])

In [ ]:
np.array([3.14,1,2,3,'string'])

array(['3.14', '1', '2', '3', 'string'], dtype='<U32')

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

Create arrays ffrom scratch

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,3))

array([[0.52337866, 0.07041072, 0.47175119],
       [0.26628333, 0.58922836, 0.92655677],
       [0.82282773, 0.23515883, 0.4569753 ]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[-0.6469596 ,  1.09900283, -2.33382732],
       [ 0.81433582, -0.53960283, -0.69219173],
       [ 0.29427701,  0.11541731,  0.9460377 ]])

In [ ]:
np.random.randint(0,10,(3,4))

array([[1, 2, 5, 5],
       [2, 5, 0, 3],
       [9, 8, 1, 3]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Numpy array attributes

In [ ]:
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [ ]:
print(x3)

[[[7 3 3 6 6]
  [3 6 8 5 7]
  [5 0 3 9 5]
  [2 9 0 2 0]]

 [[6 6 5 7 7]
  [4 9 2 5 0]
  [0 0 3 2 1]
  [8 3 3 5 4]]

 [[5 7 0 4 0]
  [4 9 7 3 7]
  [2 3 3 9 1]
  [3 8 2 4 3]]]


In [ ]:
x2.ndim

2

In [ ]:
x2.shape

(3, 4)

In [ ]:
x3.size

60

In [ ]:
x3.dtype

dtype('int64')

# Array Slicing

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[4:10:3]

array([4, 7])

In [ ]:
x[::-2]

array([9, 7, 5, 3, 1])

In [ ]:
x[5::-2]

array([5, 3, 1])

In [ ]:
x2

array([[1, 2, 5, 6],
       [7, 0, 8, 8],
       [2, 5, 5, 0]])

In [ ]:
x2[:2,:3]

array([[1, 2, 5],
       [7, 0, 8]])

In [ ]:
x2[0,:]

array([1, 2, 5, 6])

In [ ]:
x2[:,0]

array([1, 7, 2])

In [ ]:
x2

array([[1, 2, 5, 6],
       [7, 0, 8, 8],
       [2, 5, 5, 0]])

In [ ]:
x2_sub = x2[:2,:2]
x2_sub

array([[1, 2],
       [7, 0]])

In [ ]:
x2_sub[0,0] = 99
x2_sub

array([[99,  2],
       [ 7,  0]])

In [ ]:
x2

array([[99,  2,  5,  6],
       [ 7,  0,  8,  8],
       [ 2,  5,  5,  0]])

In [ ]:
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy

array([[99,  2],
       [ 7,  0]])

In [ ]:
x2_sub_copy[0,0] = 45
x2_sub_copy

array([[45,  2],
       [ 7,  0]])

In [ ]:
x2

array([[99,  2,  5,  6],
       [ 7,  0,  8,  8],
       [ 2,  5,  5,  0]])

# Reshaping of arrays

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
g = np.arange(1,10).reshape((3,3))
g

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

np.concatenate
np.vstack
np.split

Array arithmetic

In [ ]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [ ]:
x+5

array([5, 6, 7, 8])

In [ ]:
x-5

array([-5, -4, -3, -2])

In [ ]:
x*5

array([ 0,  5, 10, 15])

In [ ]:
x/2

array([0. , 0.5, 1. , 1.5])

In [ ]:
-x

array([ 0, -1, -2, -3])

In [ ]:
x**2

array([0, 1, 4, 9])

In [ ]:
- (0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
x+2

array([2, 3, 4, 5])

In [ ]:
np.add(x,2)

array([2, 3, 4, 5])

In [ ]:
np.abs(-x)

array([0, 1, 2, 3])

In [ ]:
np.max(x)

3

In [ ]:
x = np.random.randint(10,100,(3,4))
x

array([[96, 62, 19, 58],
       [55, 68, 11, 94],
       [98, 81, 31, 95]])

In [ ]:
x.sum()

768

In [ ]:
x.sum(axis=1)

array([235, 228, 305])

In [ ]:
x.mean(axis=0)

array([83.        , 70.33333333, 20.33333333, 82.33333333])

In [ ]:
x.std()

29.425046020921247